server:
  port: 8083
  
spring:
  cloud:
    gateway:
      routes:
      - id: sgd-api
        uri: http://localhost:8081
        predicates:
        - Path=/msw/**
        filters:
        - RewritePath=/msw/(?<segmento>.*), /sgd-api/$\{segmento}
